# 2013-11-13T16:39:56 by gatox .travis.yml Continuous Integration by Ninja-IDE
language: python

python:
  #- 2.7
  #- 3.3
  - 3.4

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get update -qqm
  - sudo apt-get install -qqm wget build-essential python3
  #- sudo apt-get uninstall -qqm python
  - sudo "python -3.4 -m pip install --upgrade pip"
  - sudo "python -3.4 -m pip install pyqt5"
  - sudo "python -3.4 -m pip install sip"
  - sudo ls .
  - sudo ls ..
  - sudo ls ~/
  - sudo ls ~/build
  - sudo ls ~/builds
  - cd $TRAVIS_BUILD_DIR
  - python -3.4 -c 'import PyQt5, PyQt5.QtGui, PyQt5.QtCore, PyQt5.QtWidgets, sip'  # to test if compile its ok

install: true

before_script: rm --recursive --force --verbose *.py[cod]

script: ./run-tests ninja_tests/tools/jsonmanager

after_script: true

after_success: true

after_failure: true

notifications:
  irc:
      channels: "irc.freenode.org#ninja-ide"
      template:
          - "%{repository}@%{branch}: %{message}(%{build_url})"
          - "Build: %{build_number}, SHA: %{commit}, Committer: %{author}, Diff: %{compare_url}"
      on_success: always
      on_failure: always
      use_notice: true  # false to disable
  email:
      recipients: dojo@ninja-ide.org
      template:
          - "%{repository}@%{branch}: %{message}(%{build_url})"
          - "Build: %{build_number}, SHA: %{commit}, Committer: %{author}, Diff: %{compare_url}"
      on_success: change
      on_failure: always

cache: apt
