# 2013-11-13T16:39:56 by gatox .travis.yml Continuous Integration by Ninja-IDE
language: python

python:
  #- 2.7
  #- 3.3
  - 3.4

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  #- sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
  #- sudo apt-add-repository ppa:beineri/opt-qt551 -y
  - sudo apt-get update -qqm
  - sudo apt-get install -qqm wget build-essential python3
  #- sudo apt-get install -qqm wget build-essential python3 python3-dbg# python-dev
  #- sudo apt-get install -qqm qt-latest
  - sudo pip install --upgrade pip
  #- sudo apt-get install  python3-pyqt5
  #- sudo apt-get install  pyqt5-dev-tools
  #- sudo apt-get install -qqm qtbase5
  #- sudo apt-get install -qqm qt5-qmake
  #- sudo apt-get install  qtbase5-dev-tools
  #- sudo apt-get install -qqm qtbase5-dev-tools
  #- sudo apt-get install -qqm libqt5-dev
  #- sudo apt-get install -qqm python-sip-dev
  #- sudo apt-get install  python3-sip
  #- sudo apt-get install  python3-sip-dbg
  #- wget --quiet --output-document=QT_5.run http://download.qt.io/development_releases/qt/5.5/5.5.0-rc/qt-opensource-linux-x64-5.5.0-rc.run
  #- sudo chmod +x QT_5.run
  #- ./QT_5.run
  # install SIP
  #- sudo ls /home/travis/
  #- cd /tmp
  #- wget --quiet --output-document=sip.tar.gz https://sourceforge.net/projects/pyqt/files/sip/sip-4.17/sip-4.17.tar.gz
  #- tar -xf sip.tar.gz
  #- cd sip-4.17
  #- python -B configure.py
  #- make --quiet
  #- sudo make --quiet install
  # install PyQt
  #- cd /tmp
  #- wget --quiet --output-document=pyqt.tar.gz https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.5.1/PyQt-gpl-5.5.1.tar.gz 
  #- tar -xf pyqt.tar.gz
  #- cd PyQt-gpl-5.5.1
  - sudo pip install pyqt5
  - sudo pip install sip
  - sudo ls .
  - sudo ls ..
  - sudo ls ~/
  - sudo ls ~/build
  - sudo ls ~/builds
  #- sudo ls ~/Qt5/5.5.1/
  #- sudo python configure.py --qmake ~/Qt5/5.5.1/gcc_64/bin/qmake --sip-incdir ../sip-4.17/siplib
  #- sudo python configure –prefix /usr
  #- make --quiet
  #- sudo make --quiet install
  - cd $TRAVIS_BUILD_DIR
  #- sudo apt-get update -qqm
   - python -c 'import PyQt5, PyQt5.QtGui, PyQt5.QtCore, PyQt5.QtWidgets, sip'  # to test if compile its ok

install: true

before_script: rm --recursive --force --verbose *.py[cod]

script: ./run-tests ninja_tests/tools/jsonmanager

after_script: true

after_success: true

after_failure: true

notifications:
  irc:
      channels: "irc.freenode.org#ninja-ide"
      template:
          - "%{repository}@%{branch}: %{message}(%{build_url})"
          - "Build: %{build_number}, SHA: %{commit}, Committer: %{author}, Diff: %{compare_url}"
      on_success: always
      on_failure: always
      use_notice: true  # false to disable
  email:
      recipients: dojo@ninja-ide.org
      template:
          - "%{repository}@%{branch}: %{message}(%{build_url})"
          - "Build: %{build_number}, SHA: %{commit}, Committer: %{author}, Diff: %{compare_url}"
      on_success: change
      on_failure: always

cache: apt
